version: '3.4'

services:
  daprweb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  daprapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  daprgrpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5050"
